### ISSUE TITLE
Help file name too long

### ISSUE THREAD

**Issue by adamdray** [TinyMUSH/TinyMUSH#12]
I'm getting this error when I start up:

210309.122859 netmush CNF/SYNTX: main:add_helpfile: Helpfile help filename too long

I have this in my .conf:

text_home               /Users/Adam1/MUD/TinyMUSH-latest/TinyMUSH/game/share/tinymush/

Looks like the file path has to fit in a 64-byte SBUF.

**Comment by belisariussmith** [comment]
Likely due to an old limitation from PATH_MAX, MAXPATHLEN, etc. I would just remove that check in conf.c or you could increase the SBUF_SIZE to 128 and seeing if that causes any unintended consequences.Yours Truly,Belisarius
-------- Original message --------From: adamdray <notifications@github.com> Date: 3/9/21  1:38 PM  (GMT-06:00) To: TinyMUSH/TinyMUSH <TinyMUSH@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [TinyMUSH/TinyMUSH] Help file name too long (#12) 
I'm getting this error when I start up:
210309.122859 netmush CNF/SYNTX: main:add_helpfile: Helpfile help filename too long
I have this in my .conf:
text_home               /Users/Adam1/MUD/TinyMUSH-latest/TinyMUSH/game/share/tinymush/
Looks like the file path has to fit in a 64-byte SBUF.

**Comment by adamdray** [comment]
Yeah, I doubled SBUF_SIZE and that got me past it. But now it can't find the helpfile:

> 210309.151733 netmush HLP/LOAD : main:add_helpfile: Helpfile help not found at path: /Users/Adam1/MUD/TinyMUSH-latest/TinyMUSH/game/share/tinymush/help.txt, MAXPATHLEN is 1024

after I added a bit of path logging in conf.c:

`cf_log(player, "HLP", "LOAD", confcmd, "Helpfile %s not found at path: %s, MAXPATHLEN is %d", fcmd, fpath, MAXPATHLEN);`

-bash-3.2$ ls -l /Users/Adam1/MUD/TinyMUSH-latest/TinyMUSH/game/share/tinymush/help.txt
> -rw-r--r--  1 Adam1  staff  593966 Mar  9 15:17 /Users/Adam1/MUD/TinyMUSH-latest/TinyMUSH/game/share/tinymush/help.txt

**Comment by adamdray** [comment]
Never mind. I think I have an extra .txt in there. I changed the cf_log to print `s` instead of `fpath` and got help.txt.txt.

**Comment by adamdray** [comment]
The default netmush.conf file has these lines:

`# -- Main help files.
#
#help_users      help    help.txt
#help_wizards    wizhelp wizhelp.txt
#help_quick      qhelp   qhelp.txt
`
If you comment them out, they won't work, because conf.c adds a .txt to the filename automatically. 
The netmush.conf file should say:

`help_users      help    help
help_wizards    wizhelp wizhelp
help_quick      qhelp   qhelp`

I don't know why they're commented-out by default.

**Comment by belisariussmith** [comment]
hahaha that is strange, it would probably be best to have that code taken out entirely (which adds the .txt extension) - why force that on the coder/admin? Also, it can only lead to confusion like you just experienced.

**Comment by adamdray** [comment]
Really, just check for the .txt and add it if needed?

**Comment by belisariussmith** [comment]
I guess its personal preference, I despise file extensions, but then again I grew up on UNIX, so I admit I'm biased
