### ISSUE TITLE
3.2 release is actually 3.3.0.8

### ISSUE THREAD

**Issue by callicrates** [TinyMUSH/TinyMUSH#2]
The tar file V3.2.tar.gz actually contains 3.3.0.8 according to PACKAGE_VERSION inside the configure script.

Git history does not appear to go back far enough to let me check out a copy of 3.2.

Can you take a look at this?

**Comment by EddyBeaupre** [comment]
Yes and no...

Complete history up to 3.2 is in the Historical-TinyMUSH repository (https://github.com/TinyMUSH/Historical-TinyMUSH). Since 3.3 change many things, i've decided to split the repository in two distinct repository.

The so called 3.2 release in the 3.3 repository is not the official 3.2 release, it's more a ghost that i forgot ro remove. Official releases are on the tinymush website (https://www.tinymush.net, or more precisely https://downloads.tinymush.net/TinyMUSH/3.2/Release/tm32p0.tar.gz) and that one is correct.
